language: node_js

node_js:
  - '10'
  - '12'

sudo: false

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - 'yarn test'

jobs:
  include:
    - stage: Lint
      node_js: node
      script: yarn lint
    - stage: Produce Coverage
      node_js: node
      script: yarn test:coverage && yarn codecov
    - stage: Build
      node_js: node
      script: yarn build
